# Run provenance for every generated results file.
#
# WHY: none of this repo's result JSONs recorded what produced them.
# rag/data/qwen_rag_mlx_results.json does not say which model generated it,
# which TOP_K built its prompts, whether FK annotations were on, what
# max_tokens was, or which commit was checked out. That was survivable while
# one person held it all in their head; it stops being survivable the moment
# anything compares runs across time, because a metric change cannot be
# attributed to a cause if the artifact does not record what the cause was.
#
# WHY A SIBLING FILE, NOT A `_manifest` KEY: every results file in this repo
# is a JSON *list*, and every consumer -- normalize.py, rag/score_rag.py,
# evaluation/execute_queries.py, visualize_cross_arm_304.py, demo_ui/ --
# does `json.load(f)` and immediately iterates it. Turning the top level into
# a dict to hold a `_manifest` key would break all of them at once. So the
# manifest is written next to the results as `<name>.manifest.json`:
# purely additive, impossible for an existing reader to trip over, and it
# survives the results file being regenerated by a resumable run.
#
# Usage (one call, right after the results file is written):
#
#     from run_manifest import write_manifest
#     write_manifest(output_path, script=__file__, model=MODEL, n_cases=len(cases),
#                    max_tokens=args.max_tokens, temp=0.0, samples=1)
#
# Reading one back:
#
#     from run_manifest import manifest_path
#     json.loads(manifest_path("rag/data/qwen_rag_mlx_results.json").read_text())

import hashlib
import json
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent

MANIFEST_SUFFIX = ".manifest.json"

# Bumped only when the manifest's own field layout changes incompatibly, so
# a consumer reading an old artifact can tell which shape it is looking at.
MANIFEST_SCHEMA_VERSION = 1


def manifest_path(results_path) -> Path:
    """`rag/data/x.json` -> `rag/data/x.manifest.json`. Also correct for a
    results path with no .json suffix."""
    p = Path(results_path)
    stem = p.name[: -len(p.suffix)] if p.suffix else p.name
    return p.with_name(stem + MANIFEST_SUFFIX)


def _git(*args) -> str | None:
    """Best-effort git query. Returns None outside a repo or without git --
    a manifest that is missing its SHA is far better than a generation run
    that dies at the finish line because git is not installed."""
    try:
        out = subprocess.run(
            ["git", *args], cwd=REPO_ROOT, capture_output=True, text=True, timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return out.stdout.strip() if out.returncode == 0 else None


def _package_version(name: str) -> str | None:
    try:
        from importlib.metadata import PackageNotFoundError, version
        try:
            return version(name)
        except PackageNotFoundError:
            return None
    except ImportError:
        return None


def _sha256_of(path: Path) -> str | None:
    try:
        h = hashlib.sha256()
        with path.open("rb") as fh:
            for chunk in iter(lambda: fh.read(1 << 20), b""):
                h.update(chunk)
        return h.hexdigest()
    except OSError:
        return None


def build_manifest(results_path=None, **fields) -> dict:
    """Assembles the provenance record. Everything the caller passes in
    **fields is merged in verbatim (model, adapter, top_k, include_fk,
    max_tokens, temp, samples, n_cases, ...) -- this function's own job is
    only the parts a caller should never have to hand-type: the environment,
    the git state, the timestamp, and the output hash."""
    sha = _git("rev-parse", "HEAD")
    status = _git("status", "--porcelain")

    manifest = {
        "manifest_schema_version": MANIFEST_SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "git_sha": sha,
        # A SHA only means something if the tree it names was clean when the
        # artifact was produced. Recorded rather than enforced -- a dirty-tree
        # run is a legitimate thing to do while iterating, it just must not be
        # mistaken later for a run that pins to a published commit.
        "git_dirty": (bool(status) if status is not None else None),
        "git_branch": _git("rev-parse", "--abbrev-ref", "HEAD"),
        "python_version": platform.python_version(),
        "platform": f"{platform.system()} {platform.machine()}",
        "mlx_lm_version": _package_version("mlx-lm"),
        "mlx_version": _package_version("mlx"),
    }
    manifest.update(fields)

    if results_path is not None:
        rp = Path(results_path)
        manifest["results_file"] = str(rp.relative_to(REPO_ROOT)) if rp.is_absolute() and rp.is_relative_to(REPO_ROOT) else str(rp)
        manifest["results_sha256"] = _sha256_of(rp)
        manifest["results_bytes"] = rp.stat().st_size if rp.exists() else None

    return manifest


def read_manifest(results_path) -> dict | None:
    """The manifest for `results_path`, or None if it has none. Returns None
    rather than raising for a missing OR malformed file: every artifact in
    this repo predates manifests, so "no provenance recorded" has to be an
    ordinary, non-fatal answer for a reader to get."""
    p = manifest_path(results_path)
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def write_manifest(results_path, script=None, **fields) -> Path:
    """Writes `<results_path stem>.manifest.json` next to the results file
    and returns its path. `script` is normally just `__file__`; it is stored
    repo-relative so the manifest reads the same on any machine."""
    if script is not None:
        sp = Path(script).resolve()
        fields.setdefault("script", str(sp.relative_to(REPO_ROOT)) if sp.is_relative_to(REPO_ROOT) else sp.name)

    manifest = build_manifest(results_path, **fields)
    out = manifest_path(results_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return out


if __name__ == "__main__":
    # `python run_manifest.py <results.json>` prints what a manifest for that
    # file would contain, without writing anything -- handy for eyeballing the
    # git/env capture before wiring the call into a 40-minute generation run.
    target = sys.argv[1] if len(sys.argv) > 1 else None
    print(json.dumps(build_manifest(target), indent=2))
